### ISSUE TITLE
Problems when going from depth=7 to depth=8

### ISSUE THREAD

**Issue by RasmusRPaulsen** [octree-nn/ognn-pytorch#2]
Hi,
Thank you very much for making this code available - it is very inspiring.
To get a better understanding, we are trying to train different models. First, a basic AE using the same setup as you use for shapenet, but with a different anatomical set.

We have succesfully trained a full_depth=4 and max_depth=7 and can do both encoding and decoding. 

We have made custom and simple encoding and decoding scripts.

We have also succesfully trained a full_depth=4 and max_depth=8 model. When the model is trained, the encoding works.

The problem comes when decoding the 4,8 model. Something weird is going on in the octree-dual octree code. 

In nn.py here:

class GraphPad(torch.nn.Module):

  def __init__(self):
    super().__init__()

  def forward(self, x: torch.Tensor, octree: OctreeD, depth: int):
    # pad zeros to get features for the original octree nodes
    octree_mask = octree.graphs[depth].octree_mask
    out = x.new_zeros(octree_mask.shape[0], x.shape[1])
    out[octree_mask] = x  # pad zeros for internal octree nodes
    return out

octree_mask is None for depth=5 and an exception is thrown when trying to get the shape of None.

Any comments are welcome!

Thanks!
Rasmus

**Comment by wang-ps** [comment]
Thanks for your interest in our paper!  
For your reference, the experiments on DFaust use octrees with depth 8, the instructions are [here](https://github.com/octree-nn/ognn-pytorch?tab=readme-ov-file#4-unsupervised-surface-reconstruction-with-dfaust).
On the other hand, if possible, please provide me with some examples to reproduce the error. My feeling is that the issue is very easy to fix.

**Comment by RasmusRPaulsen** [comment]
Thank you for the swift answer!
I have created a simple encode-decode test with associated data. You can find it as a zip file here:

https://people.compute.dtu.dk/rapa/octreenn/

let me know if you can not get the file?

It should work by just placing the octree_nn_test.py file in the base directory of ognn-pytorch.

The pipeline is a simple as I could think of. 
1) Encode a point cloud into a latent vector and store it
2) Read the latent vector and decode it and generate the mesh

It works for depth 4,7 and fails on 4,8.

Please let me know if I have misunderstood the basics?

Thanks for the pointer to the DFaust data - let me know if I should go that direction instead?

Best,
Rasmus

**Comment by wang-ps** [comment]
I checked your code. It is easy to fix.

The reason is that the original model is configed to work with octree  depth 4,7. To make it work with depth 4,8, you should change the model configuration, or train the model with octree depth 5,8.

The encoder and decoder has 4 stages. So the network takes an octree with depth 7 and downsamples it from 7 to depth 6, 5, and 4. 

https://github.com/octree-nn/ognn-pytorch/blob/master/ognn/ounet.py#L71C1-L76C47
```
  def config_network(self):
    self.n_node_type = 5
    self.encoder_blk_nums = [3, 3, 3, 3]
    self.decoder_blk_nums = [3, 3, 3, 3]
    self.encoder_channels = [32, 64, 128, 256]
    self.decoder_channels = [256, 128, 64, 32]
```
On easy fix is to overwrite the above code to 

```
  def config_network(self):
    self.n_node_type = 6
    self.encoder_blk_nums = [3, 3, 3, 3, 3]
    self.decoder_blk_nums = [3, 3, 3, 3, 3]
    self.encoder_channels = [32, 64, 128, 256, 256]
    self.decoder_channels = [256, 256, 128, 64, 32]
```

**Comment by RasmusRPaulsen** [comment]
Thank you for the response!
I made it work following your advice on using depth=5,8. 
Thanks again!
